const { logger } = require('../../../config/logger');

// ============================================================
// Generation Metrics — RAG Quality & Groundedness Evaluator
// ============================================================
// Evaluates generated answers across three pillars:
//   1. Answer Relevance: Does the response directly address the question?
//   2. Faithfulness / Groundedness: Are all claims supported by retrieved context without hallucination?
//   3. Context Utilization: How effectively were the retrieved chunks utilized?

class GenerationMetrics {
  /**
   * @param {object} [options]
   * @param {object} [options.llmProvider]
   */
  constructor(options = {}) {
    this.llmProvider = options.llmProvider || null;
  }

  /**
   * Evaluate generated answer quality across all pillars.
   *
   * @param {object} params
   * @param {string} params.question - The input query
   * @param {string} params.generatedAnswer - Answer generated by RAG
   * @param {Array<object>} params.retrievedChunks - Context chunks supplied to LLM
   * @param {Array<object>} [params.citations=[]] - Citations attached to answer
   * @param {string} [params.expectedAnswer] - Optional ground-truth answer
   * @returns {Promise<{ answerRelevance: number, faithfulness: number, contextUtilization: number, overallScore: number, explanation: object }>}
   */
  async evaluate({
    question,
    generatedAnswer,
    retrievedChunks = [],
    citations = [],
    expectedAnswer = null,
  }) {
    if (!generatedAnswer || !generatedAnswer.trim()) {
      return {
        answerRelevance: 0.0,
        faithfulness: 1.0,
        contextUtilization: 0.0,
        overallScore: 0.0,
        explanation: { reason: 'EMPTY_ANSWER' },
      };
    }

    // 1. Context Utilization
    const contextUtilization = this._calculateContextUtilization(retrievedChunks, citations, generatedAnswer);

    // 2. Answer Relevance
    const answerRelevance = this._calculateAnswerRelevance(question, generatedAnswer, expectedAnswer);

    // 3. Faithfulness / Groundedness
    let faithfulness = this._calculateFaithfulness(generatedAnswer, retrievedChunks);

    // If LLM provider available, can optionally refine faithfulness score
    if (this.llmProvider && retrievedChunks.length > 0) {
      try {
        const llmJudgeScore = await this._evaluateWithLLMJudge(question, generatedAnswer, retrievedChunks);
        if (llmJudgeScore != null) {
          faithfulness = llmJudgeScore;
        }
      } catch (err) {
        logger.debug({ error: err.message }, 'LLM judge evaluation bypassed, using heuristic');
      }
    }

    const overallScore = Number(
      ((answerRelevance * 0.4) + (faithfulness * 0.4) + (contextUtilization * 0.2)).toFixed(4)
    );

    return {
      answerRelevance: Number(answerRelevance.toFixed(4)),
      faithfulness: Number(faithfulness.toFixed(4)),
      contextUtilization: Number(contextUtilization.toFixed(4)),
      overallScore,
      explanation: {
        citedChunksCount: citations.length,
        retrievedChunksCount: retrievedChunks.length,
        answerLength: generatedAnswer.length,
      },
    };
  }

  /**
   * Calculate Context Utilization (fraction of retrieved chunks cited/present).
   */
  _calculateContextUtilization(retrievedChunks, citations, answer) {
    if (!Array.isArray(retrievedChunks) || retrievedChunks.length === 0) return 0.0;

    const totalRetrieved = retrievedChunks.length;
    const citedChunkIds = new Set(citations.map((c) => c.chunkId));

    let utilizedCount = 0;
    for (const chunk of retrievedChunks) {
      if (citedChunkIds.has(chunk.chunkId)) {
        utilizedCount += 1;
      } else if (chunk.content) {
        // Check if key 5-word phrases from chunk appear in answer
        const snippet = chunk.content.slice(0, 50).trim().toLowerCase();
        if (answer.toLowerCase().includes(snippet)) {
          utilizedCount += 1;
        }
      }
    }

    return Math.min(1.0, utilizedCount / totalRetrieved);
  }

  /**
   * Calculate Answer Relevance using query-answer token alignment and semantic coverage.
   */
  _calculateAnswerRelevance(question, answer, expectedAnswer) {
    if (!question || !answer) return 0.0;

    const qTokens = question
      .toLowerCase()
      .replace(/[^a-z0-9\s]/g, '')
      .split(/\s+/)
      .filter((t) => t.length > 2);

    const aLower = answer.toLowerCase();

    if (qTokens.length === 0) return 1.0;

    let matched = 0;
    for (const token of qTokens) {
      if (aLower.includes(token)) matched += 1;
    }

    let score = (matched / qTokens.length) * 0.7;

    // Direct answer length and clarity bonus
    if (answer.length > 20 && !answer.includes("couldn't find enough information")) {
      score += 0.3;
    }

    // Expected answer alignment if provided
    if (expectedAnswer) {
      const expTokens = expectedAnswer.toLowerCase().split(/\s+/).filter((t) => t.length > 2);
      if (expTokens.length > 0) {
        const expMatched = expTokens.filter((t) => aLower.includes(t)).length;
        score = (score * 0.5) + ((expMatched / expTokens.length) * 0.5);
      }
    }

    return Math.min(1.0, Math.max(0.0, score));
  }

  /**
   * Calculate Faithfulness / Groundedness against retrieved context.
   */
  _calculateFaithfulness(answer, retrievedChunks) {
    if (!Array.isArray(retrievedChunks) || retrievedChunks.length === 0) {
      // If no chunks and model correctly stated no information found
      if (answer.includes("couldn't find enough information") || answer.includes("cannot answer")) {
        return 1.0;
      }
      return 0.0;
    }

    const combinedContext = retrievedChunks
      .map((c) => (c.content || '').toLowerCase())
      .join(' ');

    const sentences = answer
      .split(/[.!?]+/)
      .map((s) => s.trim())
      .filter((s) => s.length > 10);

    if (sentences.length === 0) return 1.0;

    let supportedSentences = 0;
    for (const sentence of sentences) {
      const sentenceTokens = sentence
        .toLowerCase()
        .replace(/[^a-z0-9\s]/g, '')
        .split(/\s+/)
        .filter((t) => t.length > 3);

      if (sentenceTokens.length === 0) {
        supportedSentences += 1;
        continue;
      }

      const matchCount = sentenceTokens.filter((t) => combinedContext.includes(t)).length;
      if ((matchCount / sentenceTokens.length) >= 0.5) {
        supportedSentences += 1;
      }
    }

    return supportedSentences / sentences.length;
  }

  /**
   * LLM-as-a-judge evaluation for nuanced faithfulness verification.
   */
  async _evaluateWithLLMJudge(question, answer, retrievedChunks) {
    const contextText = retrievedChunks.map((c, i) => `[Source ${i + 1}]: ${c.content}`).join('\n\n');
    const prompt = `You are an expert RAG evaluator. Evaluate the faithfulness of the generated answer against the retrieved source context on a scale from 0.0 to 1.0.
Question: ${question}
Retrieved Context:
${contextText}
Generated Answer:
${answer}

Output ONLY a JSON object: {"faithfulness": <number between 0.0 and 1.0>}`;

    const rawResponse = await this.llmProvider.generateAnswer({
      systemPrompt: 'You evaluate factual consistency. Output JSON only.',
      userPrompt: prompt,
    });

    try {
      const jsonMatch = rawResponse.match(/\{[\s\S]*\}/);
      if (jsonMatch) {
        const parsed = JSON.parse(jsonMatch[0]);
        if (typeof parsed.faithfulness === 'number') {
          return Math.min(1.0, Math.max(0.0, parsed.faithfulness));
        }
      }
    } catch {
      // Return null on parsing failure
    }
    return null;
  }
}

const generationMetrics = new GenerationMetrics();

module.exports = {
  GenerationMetrics,
  generationMetrics,
};
